### PR TITLE
WIP: windows port

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Comment by sylvestre** [comment]
@oSoMoN Would you be able to finish this PR ? :) thanks

**Comment by oSoMoN** [comment]
My experience with Windows is rusty (pun intended) at best, and I have no Windows machine handy, but I can take a look when time permits.

**Comment by oSoMoN** [comment]
@calixteman instead of a custom, platform-specific `split_at_eol` macro, why not use [str::lines()](https://doc.rust-lang.org/std/primitive.str.html#method.lines) from the standard library?

**Comment by oSoMoN** [comment]
Per https://github.com/uutils/diffutils/issues/3#issuecomment-2068192151, I'm closing this PR.

**Pull request closed without merging**
