### PR TITLE
Switch to a custom Myers-based LCS engine

### PR DESCRIPTION
**Pull request by kov**
This is a big one. It basically allows our version of diff to be used on larger files, which right now crash due to an impossibly large allocation, due to the library we use implementing the LCS algorithm using a full matrix matching lines of both files.

I looked at implementing this on the library, but the author already has a patch for months and has been unresponsive. I also think it makes sense to have our own engine that can be customized and optimized as required by the goals of the tool rather than relying on a library which may be more conservative. The author mentioned in their PR that the plan there is to make the Myers diagonal search optional due to the pathological cases - which to me means heuristics will probably not be welcome.

I split the actual feature in 3 commits:

- implementation and adoption of the Myers diagonal search
- importing some heuristics used by GNU diff to bail out on "good enough" or "too expensive" searches
- adapting yet another heuristic to give up on the algorithm completely for files that seem just too large and different

See each commit for more details of performance, it is looking pretty good. I would prefer to keep the commits separate, like I did for the cmp optimizations, so that we have a good base for debugging and bisecting if we find some weird corner case.

Tests all pass, the diffs produced I looked manually at seem to have good quality. To weed out any corner cases (and I did find some!) I have been running the following script for the last couple of days. Since I last fired it up it's been going for over 12 hours now, basically diffing every single text and source code file I have in my home directory (over 370k files, I have multiple browser code bases fwiw) against /etc/passwd, an empty file, the previous file, all of them back and forth, then trying to apply it with patch and checking for correctness for each of those. So far no further issues found!

```python
#!/bin/env python3
import os
import subprocess
import sys
import shutil

def run_diff(a, b):
    shutil.copyfile(a, "a");
    shutil.copyfile(b, "b");
    ret = subprocess.run(f"./target/debug/diffutils diff a b".split(' '), stdout=open('diff', 'w'))
    print(f"ret: {ret}")
    if ret.returncode < 0 or ret.returncode == 101:
        print(f"diff killed: {ret.returncode}")
        sys.exit(2)

    ret = subprocess.run(f"patch -p0 a diff".split(' '))
    print(f"ret: {ret}")
    if ret.returncode != 0:
        print(f"patch failed: {ret.returncode}")
        sys.exit(2)

    assert open('a', 'rb').read() == open('b', 'rb').read()

previous_file = '/etc/passwd'
for current_file in open('../diff.rs/text-files'):
    current_file = current_file.strip()
    print(f"Diffing {previous_file} to {current_file}")
    for reference in ['/etc/passwd', 'empty', previous_file]:
        run_diff(reference, current_file)
        run_diff(current_file, reference)
    previous_file = current_file
```

### CODE REVIEW

**Comment by sylvestre** [comment]
Interesting. 
Did you try with hyperfine for benchmarking ? Thanks

Maybe create a BENCHMARKING.md file to document the improvement ?

**Comment by kov** [comment]
> Interesting. Did you try with hyperfine for benchmarking ? Thanks

Yep! There are some details in the individual commit messages, but the most important improvement from my perspective is being able to handle larger files at all. For very short files it should be more or less the same.

The worst case for this algorithm is completely different files, and for those (on files short enough for the old version to be able to process ;D) we have a performance regression:

Before:

> hyperfine -N -i --output=pipe --warmup 2 './target/release/diffutils diff -u t/COPYING t/COPYING2'
Benchmark 1: ./target/release/diffutils diff -u t/COPYING t/COPYING2
  Time (mean ± σ):       3.1 ms ±   0.3 ms    [User: 1.9 ms, System: 1.1 ms]
  Range (min … max):     2.6 ms …   6.9 ms    665 runs

After:

> hyperfine -N -i --output=pipe --warmup 2 './target/release/diffutils diff -u /usr/share/licenses/glib2/LGPL-2.1-or-later.txt /usr/share/licenses/coreutils-common/COPYING'
Benchmark 1: ./target/release/diffutils diff -u /usr/share/licenses/glib2/LGPL-2.1-or-later.txt /usr/share/licenses/coreutils-common/COPYING
  Time (mean ± σ):       4.8 ms ±   0.3 ms    [User: 3.9 ms, System: 0.8 ms]
  Range (min … max):     4.2 ms …   6.8 ms    444 runs

> Maybe create a BENCHMARKING.md file to document the improvement ?

Will do later today!

**Comment by sylvestre** [comment]
Please run hyperfine once with the two commands. It produces better results and comparison

**Comment by oSoMoN** [comment]
I have yet to do a proper code review, but the approach looks sound to me, and a huge undertaking, so thank you very much for this!

@sylvestre any objection to not depending on the external diff crate and re-implementing it in-house?

@kov can you add a heading comment to `src/engine.rs` that briefly explains the algorithm being implemented, together with the heuristics, like you did in the commit messages? The GNU diff implementation also quotes and provides [a (paywall) link](http://dx.doi.org/10.1007/BF01840446) to the original paper by Eugene W. Myers, could you add that too?

**Comment by kov** [comment]
FWIW, I joked on Discord that this was potentially controversial because I would completely understand not wanting to maintain a custom engine, especially if the current diff crate gets its Myers implementation merged, and maybe we could instead do a simpler decision of which "backend" to use based on file size, for instance, and potentially not support the most niche pathological cases (diffing completely different massive files is not _that_ common after all).

I don't know if you guys may have an easier time reaching the diff.rs maintainer. I would be totally fine with whatever decision, I have had a lot of fun learning about this stuff and writing this patch, but I am not emotionally tied to it, up to you!

**Comment by sylvestre** [comment]
> @sylvestre any objection to not depending on the external diff crate and re-implementing it in-house?

fine with that but I am wondering if the algo itself could not a into a different crate (in case others would like to use it) ?

**Comment by kov** [comment]
> > @sylvestre any objection to not depending on the external diff crate and re-implementing it in-house?
> 
> fine with that but I am wondering if the algo itself could not a into a different crate (in case others would like to use it) ?

I'd be fine with that, do you envision it being a crate of the uutils project or do yu mean external? When I pondered this as I was starting I thought it may make more sense if we exported the diffutils crate as a library because then you'd get the whole functionality, but there is a benefit to having the generic implementation that can be used for file lines or anything else exposed separately, I suppose.

**Comment by sylvestre** [comment]
yeah, we can create https://github.com/uutils/diff-mayers-based-lcs-engine for example :)

**Comment by kov** [comment]
Let me make it into a separate crate then, I'll start on my namespace and we can move. Will give API a bit more thought for that. I think we want to add some parameters to control the heuristics and whether we only care about a difference existing, too. But feel free to comment on the current code!

**Comment by sylvestre** [comment]
i noticed this: https://crates.io/crates/lcs-diff
did you try with it ? :)

**Comment by kov** [comment]
> i noticed this: https://crates.io/crates/lcs-diff did you try with it ? :)

I looked at this one when I was starting my research, yeah. It's basically implementing the same algorithm as the diff.rs crate that is used now, which creates a full matrix to compute the LCS:

```rust
fn create_table<T: PartialEq + Clone>(old: &[T], new: &[T]) -> Vec<Vec<u32>> {
    let new_len = new.len();
    let old_len = old.len();
    let mut table = vec![vec![0; old_len + 1]; new_len + 1];
    <snip>
    table
}
```

So it will still do a large allocation for medium files and be unable to diff very large files. I could try to reach out to the author and see if they have plans of implementing a myers-based algo.

**Comment by kov** [comment]
I have been a bit busy the last couple weeks with work, but I'll get back to this on the holidays and get the standalone crate going, I'll close this one meanwhile, thank you for the the input so far!

**Comment by oSoMoN** [comment]
Thanks Gustavo. I'm looking forward to reviewing it!

**Pull request closed without merging**
