### PR TITLE
Fix fuzz code.

### PR DESCRIPTION
**Pull request by hanbings**
link: https://github.com/uutils/diffutils/issues/7

### CODE REVIEW

**Comment by sylvestre** [comment]
@oSoMoN is that ok with you? thanks

**Comment by oSoMoN** [comment]
I suppose it doesn't matter much, but the most common case would be with `stop_early=false`.
Note that I also addressed this regression in a commit in a separate PR (https://github.com/uutils/diffutils/pull/28/commits/44a356e7c6dfca66b632e8f68c580a9b32f9d3c3), but feel free to merge this first as I'm afk for a few more days.

-------- Message d'origine --------

**Comment by sylvestre** [comment]
sorry but i took @oSoMoN as he was the first :)

**Comment by hanbings** [comment]
> sorry but i took @oSoMoN as he was the first :)

no problem. Thank you.

**Pull request closed without merging**
