### PR TITLE
Rename the `diffutils` binary to `diff`,

### PR DESCRIPTION
**Pull request by oSoMoN**
in preparation for the future implementation of other binaries (cmp, sdiff and diff3)

### CODE REVIEW

**Comment by sylvestre** [comment]
what is your plan here? Create new binaries ?

What about doing the same as coreutils ? One main binaries (or individual programs)
and if you do `ln -s diffutils diff` or `ln -s diffutils cmp`, it will change the behavior of the command.

**Comment by oSoMoN** [comment]
I was thinking of individual binaries, but I must admit I didn't look at how it's done for coreutils, and I suppose it makes sense to do something similar. I'll take a look later, in the meantime I'm leaving this PR open.

**Comment by sylvestre** [comment]
the main adv is the size of the binaries as Rust bins have a tendency to be bigger than C :)

**Comment by oSoMoN** [comment]
Closing, as this is definitely being obsoleted by Gustavo's work in #88.

**Pull request closed without merging**
